name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install SuiteSparse (dependency for scikit-sparse)
      run: sudo apt-get install -y libsuitesparse-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]  # Install package along with dev dependencies
        pip install scikit-sparse
    - name: Clean up build directory
      run: rm -rf ./build
    - name: Run Linters and Formatters
      run: |
        pre-commit run --all-files
    - name: Run Tests
      run: |
        pytest
